merge __init__() into start() function (#17)
* remove __init__, which is likely cause of Uncaught AttributeError: 'Menu' object has no attribute 'render'